### ISSUE TITLE
Errors while running batch1_integrate.R script

### ISSUE THREAD

**Issue by ankur-26197** [zhenwang100/scKD#1]
Hello,

I am trying to run `batch1_integrate.R` on a publicly available dataset. Running line # 14, I get an error message ```Error in lapply(data_list, FUN = function(sample_data) { : 
  object 'data_list' not found```
  which is obvious as data_list is not initialised and you are using lapply on it. Also I can see `sample` variable being used which will give error. 

Can you please help me?

  Thank you.

**Comment by zhenwang100** [comment]
Sorry for the error. Line #14 should be lapply(samples, FUN = function(sample) {


________________________________
发件人: Ankur Singh ***@***.***>
发送时间: 2022年5月4日 20:24
收件人: zhenwang100/scKD ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zhenwang100/scKD] Errors while running batch1_integrate.R script (Issue #1)


Hello,
I am trying to run batch1_integrate.R on a publicly available dataset. Running line # 14 I get the issue Error in lapply(data_list, FUN = function(sample_data) { : object 'data_list' not found
which is obvious as data_list is not initialised and you are using lapply on it. Also I can see sample variable which will give error. Can you please help me?
Thank you.

―

**Comment by ankur-26197** [comment]
Thanks for the help!
