### ISSUE TITLE
Inconsistency in graphs after running batch1_intgerate.R

### ISSUE THREAD

**Issue by ankur-26197** [zhenwang100/scKD#2]
Hello,

Thanks for the help in the previous issue. I could successfully run the batch1_integrate.R and generate 3 graphs as per the code. However the UMAP plots are not split into 3 parts `before IVIG, after IVIG and health` as shown in `Fig 1` of the paper. Also the labels inside the clusters and in the legends are missing.  I am using the following Kawasaki disease dataset https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168732

Are these plots generated again while running the later scripts or I need to make code changes?

PF the file showing the UMAP plot generated.
[umap_0.1.pdf](https://github.com/zhenwang100/scKD/files/8637676/umap_0.1.pdf)

Thank you.

**Comment by zhenwang100** [comment]
These scripts are just for main analysis. If you want to produce publication-ready figures, additional modifications should be done.
For example, to split the UMAP plots by conditions, you can specify  split.by  in  DimPlot. Cluster labels and legends are added manually according to the expression of marker genes.


________________________________
发件人: Ankur Singh ***@***.***>
发送时间: 2022年5月6日 13:16
收件人: zhenwang100/scKD ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zhenwang100/scKD] Inconsistency in graphs after running batch1_intgerate.R (Issue #2)


Hello,

I could successfully run the batch1_integrate.R and generate 3 graphs as per the code. However the UMAP plots are not split into 3 parts before IVIG, after IVIG and health as shown in Fig 1 of the paper. Also the labels inside the clusters and in the legends are missing. I am using the following Kawasaki disease dataset https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE168732

Are these plots generated again while running the later scripts or I need to make code changes?

PF the file showing the UMAP plot generated.
umap_0.1.pdf<https://github.com/zhenwang100/scKD/files/8637676/umap_0.1.pdf>

Thank you.

―
