### ISSUE TITLE
Queries regarding annotating labels from batch 1 to batch2

### ISSUE THREAD

**Issue by ankur-26197** [zhenwang100/scKD#4]
Hi
As per the code and the paper, it seems that the samples collected in first phase of study i.e P1-P4 and H1-H3 were integrated and then the labels were transferred to samples from batch2. I have few questions related to it.

- Whether only cell cluster labels were transferred using Seurat's transfer utility and not the embeddings of pca and umap?
- Was the UMAP plot from the paper generated only from the `batch1.Rdata` after cell annotation?
- Was SingleR used for `batch2.Rdata` or again the labels were just transferred from `batch1.Rdata`?

Thank you.

**Comment by zhenwang100** [comment]
- Only cell cluster labels were transferred.
- The UMAP plot was generated only from the first batch.
- SingleR was not used for the second batch, as we can transfer cell labels directly from the first batch.
