### ISSUE TITLE
Deseq design parameter issue

### ISSUE THREAD

**Issue by himanshu-acog** [zhenwang100/scKD#5]
Hey,

While performing Deseq between "before and after" the design = ~patient + treatment, whereas between "before and healthy" the design = ~treatment. What is the need of adding patient only in "before and after" comparision design parameter. Also what impact will it have on the deseq results.

**Comment by zhenwang100** [comment]
Because "before and after" is a paired test for the same patient, while "before and healthy" is an unpaired test for different patients.
