### ISSUE TITLE
Issue in R/batch1_integrate.R

### ISSUE THREAD

**Issue by himanshu-acog** [zhenwang100/scKD#6]
Hey! I have an issue in computing the aggregate used in lines 84 and 85 of **R/batch1_integrate.R.** The line `cell_num<-table(Idents(comb_data))` is used to get the cell count corresponding to each column of `comb_data` and is further used to multiply with each column value of `avg_count`. However, this `cell_num` list that u got in line 84 does not guarantee the order of columns as used in the `avg_count` matrix. This results in multiplying each column value of `avg_count` with a different column value cell count. Can u verify this issue?

**Comment by zhenwang100** [comment]
Yes, we verify this. The order of cell type is consistent between  `cell_num` and   `avg_count`.
`colnames(avg_count) == names(cell_num) `

**Comment by himanshu-acog** [comment]
This might be in your case but in my case, this doesn't guarantee the same order. Hence, getting completely different results. I have to reorder the `cell_num` manually to make the order the same as `avg_count` before multiplying. I verified this on completely different datasets as well.
